### ISSUE TITLE
Perchè non usare i file di Calendar?

### ISSUE THREAD

**Issue by Emilio846** [maurofrezza/Calendari-SAVNO#2]
Ciao, anzitutto ti ringrazio per il lavoro fatto finora, l'app era veramente un aiuto molto valido. 
Io purtroppo non ho tempo da dedicarci, ma ho seguito la questione con interesse da quando l'app non funziona più.
Savno ha pubblicato sul sui sito i file .ics per Google Calendar, che mi sembrano più adatti per la scrittura dei file JSON:
https://www.savnoservizi.it/it/avvisi-e-download/download/calendari

Questi file sono testuali e hanno una struttura ripetitiva e ordinata, del tipo:
```
BEGIN:VEVENT
DTSTART:20220813T060000Z
DTSTAMP:20220217T072308Z
UID:v3ktp1hlua89m4fwdqrjbo2cz0â€‹@google.com
CREATED:20220813T080000Z
DESCRIPTION:SAVNO Raccolta VETRO
LAST-MODIFIED:20220112T081056Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:SAVNO Raccolta VETRO
TRANSP:OPAQUE
END:VEVENT
```

**Comment by maurofrezza** [comment]
Ciao Emilio,
hai ragione vanno bene anche quelli. L'importante è che la mappatura con i valori supportati sia corretta.
Posso aggiornare le note per includere questa opzione

**Comment by maurofrezza** [comment]
Aggiornate Note.md

https://github.com/maurofrezza/Calendari-SAVNO/commit/4ed5cfb5404c1765b37bf78b7720a651e1498ed9

**Comment by Emilio846** [comment]
Ciao, intendevo che magari la struttura dei file dei calendari potesse essere facilmente convertita nella struttura dei file json creati da te, bypassando il lavoro manuale di conversione ora delegato ai "volontari". Essendo la struttura ripetitiva, immagino si possa facilmente ripristinare l'automatismo che avevi creato inizialmente per dare vita alla app.

**Comment by maurofrezza** [comment]
Sono sicuramente semplici da gestire rispetto ai CSV. In ogni caso, l'intera generazione e gestione dei dati comporta un investimento di tempo che non mi sento di gestire.
